### ISSUE TITLE
Time slider scaling, start & end dates

### ISSUE THREAD

**Issue by gworthey** [sul-cidr/graves#229] opened 2018-10-22 15:29 UTC
Time slider defaults to start/end dates appropriate only for one essay (Mullaney's) -- but the other essays require much earlier dates (beginning in 17th century).

Possible options:
1) Make start/end dates customizable by essay.  (Best, but probably most complex.) 

2) Hard-code time slider to start in 1750, end in 2018.  (Will result in bad scaling for Mullaney's & McClure's essays, where the data is only 1990-2018 -- as well as highlighting time periods for which we have no data.)

3) Allow time slider to default on or off depending on the essay -- so, on for Mullaney & McClure, off for Henriot and Snyder.

**Comment by versae** [comment] 2018-10-22 15:41
Option 1 fixed in https://github.com/sul-cidr/graves/pull/223. Marked as duplicate of #220.

**Closed by versae** 2018-10-22 15:41 UTC
